name: geotraking
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.12

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  intl: ^0.19.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  webview_flutter: ^4.10.0
  url_launcher: ^6.3.1
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4
  timeago: ^3.7.0
  youtube_player_flutter: ^9.1.1
  image_picker: ^1.1.2
  change_app_package_name: ^1.4.0
  flutter_staggered_grid_view: ^0.7.0
  mysql1: ^0.20.0
  bcrypt: ^1.1.3
  device_info_plus: ^11.1.0
  package_info_plus: ^8.1.0
  pdf: ^3.11.1
  permission_handler: ^11.3.1
  open_file: ^3.5.9
  onesignal_flutter: ^5.2.6
  dropdown_search: ^6.0.1
  gauge_indicator: ^0.4.3
  flutter_shake_animated: ^0.0.5
  fl_chart: ^0.69.0
  syncfusion_flutter_datepicker: ^27.1.55
  flutter_form_builder: ^9.5.0
  flutter_plugin_android_lifecycle: ^2.0.23

  info_popup: ^4.3.1 #package utk popup tampil di kapal 
  elegant_notification: ^2.3.0 #package utk notif ketika berhasil merubah prefences
  # get: ^4.6.6 #package getX untuk state management ui
  # googleapis: ^13.2.0 #package utk ai chatbot
  # googleapis_auth: ^1.6.0 #package utk ai chatbot
  # google_generative_ai: ^0.4.6
  # web_socket_channel: ^3.0.1
  device_preview: ^1.2.0

  dio: ^5.7.0

  chat_bubbles: ^1.6.0
  flutter_chat_ui: ^1.6.15

  # mailer: ^6.2.0
  email_otp: ^3.0.2

  flutter_launcher_icons: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/ic_launcher.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"
  min_sdk_android: 21 

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/jsons/